# Generated by Django 5.2.4 on 2025-07-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiMil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mil_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
